In [1]:
from services.service import Service
from query.query import Query
import json

In [2]:
# Parameters
fund = 'undergrad'
ticker = 'VIRT'
start='2023-07-05'
end='2024-07-05'

In [3]:
service = Service()
query = Query()

In [4]:
res = service.holding_summary(fund,ticker,start,end)

res = json.loads(res)

res

{'ticker': 'VIRT',
 'active': False,
 'shares': 0,
 'initial_weight': 0.0464,
 'current_weight': 0,
 'price': 22.51,
 'total_return': 26.67,
 'total_div_return': 30.07,
 'holding_period_return': 27.65,
 'dividends': 1214.4,
 'alpha': 0.14,
 'beta': 0.3}

In [5]:
df = query.get_holding_df(fund,ticker,start,end)

df

,date,fund,ticker,name,weight_open,weight_close,shares,price,value,side,dividends,return,div_return,bmk_return,rf_return,xs_return,xs_bmk_return
0,2023-10-13,undergrad,VIRT,VIRTU FINANCIAL INC-CLASS A,0.045479,0.046385,2530.0,18.01,45565.3,1,0.0,0.013506,0.013506,-0.005448,0.000186,0.013320,-0.005634
1,2023-10-16,undergrad,VIRT,VIRTU FINANCIAL INC-CLASS A,0.046385,0.047162,2530.0,18.55,46931.5,1,0.0,0.029983,0.029983,0.011118,0.000064,0.029919,0.011054
2,2023-10-17,undergrad,VIRT,VIRTU FINANCIAL INC-CLASS A,0.047162,0.047297,2530.0,18.64,47159.2,1,0.0,0.004852,0.004852,0.001084,0.000034,0.004818,0.001049
3,2023-10-18,undergrad,VIRT,VIRTU FINANCIAL INC-CLASS A,0.047297,0.047319,2530.0,18.38,46501.4,1,0.0,-0.013948,-0.013948,-0.014351,0.000069,-0.014018,-0.014420
4,2023-10-19,undergrad,VIRT,VIRTU FINANCIAL INC-CLASS A,0.047319,0.047736,2530.0,18.35,46425.5,1,0.0,-0.001632,-0.001632,-0.009802,0.000080,-0.001712,-0.009881
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,2024-05-06,undergrad,VIRT,VIRTU FINANCIAL INC-CLASS A,0.050405,0.050353,2530.0,22.77,57608.1,1,0.0,0.010204,0.010204,0.011254,0.000133,0.010072,0.011122
137,2024-05-07,undergrad,VIRT,VIRTU FINANCIAL INC-CLASS A,0.050353,0.049507,2530.0,22.36,56570.8,1,0.0,-0.018006,-0.018006,0.001218,0.000140,-0.018146,0.001077
138,2024-05-08,undergrad,VIRT,VIRTU FINANCIAL INC-CLASS A,0.049507,0.049445,2530.0,22.42,56722.6,1,0.0,0.002683,0.002683,-0.000710,0.000116,0.002568,-0.000825
139,2024-05-09,undergrad,VIRT,VIRTU FINANCIAL INC-CLASS A,0.049445,0.050027,2530.0,22.65,57304.5,1,0.0,0.010259,0.010259,0.006120,0.000148,0.010111,0.005972
140,2024-05-10,undergrad,VIRT,VIRTU FINANCIAL INC-CLASS A,0.050027,0.049749,2530.0,22.51,56950.3,1,0.0,-0.006181,-0.006181,0.000437,0.000083,-0.006264,0.000354